### ISSUE TITLE
Outline the package in README.md

### ISSUE THREAD

**Issue by Jing-19** [UBC-MDS/lr_cd#1]
@andyzhangstat will update the README

**Comment by Jing-19** [comment]
Here is the requirement:
- a summary paragraph that describes the project at a high level
- a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)
- a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).

**Comment by andyzhangstat** [comment]
Check the pull request.
